### ISSUE TITLE
Example Not Working Properly

### ISSUE THREAD

**Issue by christopherperry** [jamesward/jaxrsbars#1]
Viewing your live sample app, I try to add a bar and hit Go! and nothing happens.

**Comment by jamesward** [comment]
Thanks for the heads up! This was due to the JS being loaded over `http` instead of `https`. 
When updating things I ran into a Mongo auth issue so I upgraded everything (on a branch):
https://github.com/jamesward/jaxrsbars/tree/dep-updates

The demo is working again with this branch.
